# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: MIT OR GPL-3.0-only
---
- name: reload systemd
  become: true
  command: systemctl --system daemon-reload
  notify:
    - restart daemons

- name: restart daemons
  command: /bin/true
  notify:
    - reset failed kubelet

- name: reset failed kubelet
  become: true
  command: systemctl reset-failed kubelet
  notify:
    - restart kubelet

- name: restart kubelet
  become: true
  service: name=kubelet state=restarted
